### PR TITLE
Remove app deploy command

### PR DESCRIPTION
**Pull request by lkostrowski**
## I want to merge this PR because 

We decided to drop 1st class support for 1-click deployment of the app to Vercel. This cost us a lot of maintenance and we don't really know any benefit of this feature.

AppStore is encouraging developers to fork the app on Github and deploy it on their own.

## Related (issues, PRs, topics)

https://github.com/saleor/apps/issues/98

## Steps to test the feature

1. `saleor app deploy` should be no longer available

## I have:

- [ ] Tested it locally and it doesn't break existing features
- [ ] Added documentation if public changes are introduced
- [ ] Added tests for my code

### CODE REVIEW

**Comment by zaiste** [comment]
@lkostrowski it's OK, but maybe we should first mark it as deprecated? a similar path you suggested for other CLI command removal?

**Review by zaiste — APPROVED** [review]

**Comment by lkostrowski** [comment]
@zaiste technically we can, but telemetry shows that its not really used 🤔 

@krzysztofwolski WDYT?

**Comment by krzysztofwolski** [comment]
If telemetry confirms that this feature was not really used, then we can drop it before new users will try to play with it. Of course, it should be marked as the next major version.

If there are some users of this feature, maybe it will be a good idea to display the deprecation message first when the command is used and schedule dropping it completely in 2-4 weeks.

**Comment by lkostrowski** [comment]
@zaiste @krzysztofwolski okay lets do it

https://github.com/saleor/saleor-cli/pull/607

@zaiste can you release it after its merged?

**Pull request merged**
