### PR TITLE
Improve deployment edge cases

### PR DESCRIPTION
**Pull request by 2can**
- set `nextjs` as default framework in case it's not available yet
- handle `id` and `uid` as deployment id
- extract common display of URLs
- improve Vercel error handling

### CODE REVIEW

**Review by zaiste — APPROVED** [review]

**Review by lkostrowski — APPROVED** [review]
Tested on `saleor dev prepare` and confirm it fixes `undefined` problem. Also `dispatch=false` works correctly.

NOT tested on limited vercel access to github

**Comment by zaiste** [comment]
@michalina-graczyk are you familiar with the _limited Vercel access to GitHub_ test scenerio?

**Comment by michalina-graczyk** [comment]
> @michalina-graczyk are you familiar with the _limited Vercel access to GitHub_ test scenerio?

After today's daily I am familiar

**Comment by michalina-graczyk** [comment]
> Tested on `saleor dev prepare` and confirm it fixes `undefined` problem. Also `dispatch=false` works correctly.
> 
> NOT tested on limited vercel access to github

@lkostrowski do you know how to set up a limited vercel access to github?

**Comment by lkostrowski** [comment]
@michalina-graczyk try here
https://github.com/settings/installations

You can configure Vercel to allow everything (this part should be working well), but also limit repositories (e.g. select none). 



Reproduction steps that will possibly reveal the problem are:
- Configure vercel integration in github to only allow selected repositories (no matter which)
- Create a new app in CLI (it will create a new repository, vercel will not have access to it by default)
- Check if this works

It's possible that it will not work, so we need to detect it and prepare a fallback path, at least document it

**Comment by michalina-graczyk** [comment]
I have reproduced it and the app is created correctly but deploy is not working 
image

**Comment by 2can** [comment]
@michalina-graczyk could you confirm you were running the command from the directory where some saleor app was present ?

**Pull request merged**
